[platformio]
default_envs = esp32dev
platforms_dir = .pio/platforms
packages_dir = .pio/packages

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4

[env:esp32dev]
board = esp32dev
build_flags =
    -DCORE_DEBUG_LEVEL=1
